name: Build & Publish Docker Image on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Lowercase repository owner
        id: repo_owner
        run: |
          lower=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')
          echo "lower=$lower" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg VERSION=${{ github.event.release.tag_name }} \
            -t ghcr.io/${{ steps.repo_owner.outputs.lower }}/traesync:${{ github.event.release.tag_name }} \
            -t ghcr.io/${{ steps.repo_owner.outputs.lower }}/traesync:latest \
            .

      - name: Push Docker Image (version tag)
        run: docker push ghcr.io/${{ steps.repo_owner.outputs.lower }}/traesync:${{ github.event.release.tag_name }}

      - name: Push Docker Image (latest tag)
        run: docker push ghcr.io/${{ steps.repo_owner.outputs.lower }}/traesync:latest
